development:
  clients:
    default:
      uri: <%= ENV['MONGOLAB_URI'] %>
      options:
        connect_timeout: 15

test:
  clients:
    default:
      uri: <%= ENV['MONGOLAB_URI'] %>
      options:
        connect_timeout: 15

production:
  clients:
    default:
      uri: <%= ENV['MONGOLAB_URI'] %>
      options:
        connect_timeout: 15